### PR TITLE
Build failures, Firefox and IE fixes

### PR DESCRIPTION
**Pull request by markrian**
This PR fixes a number of issues:
- updated devDependencies allow the package to be installed successfully
- a few fixes so that tests now pass in Firefox, IE11 and Edge
- focus-related events are now successfully created in Firefox (with supporting tests)

Cheers!

### CODE REVIEW

**Comment by markrian** [comment]
Ah, I see that PhantomJS doesn't like the new focus-related tests. I'll take a look and push new fixes for that.

**Comment by blakeembrey** [comment]
Awesome, thanks so much! :+1:

**Comment by blakeembrey** [comment]
@markrian If you're using this today, and interested, I can add you as a collaborator. I haven't used this much since I originally wrote it, so it's a little unmaintained.

**Comment by markrian** [comment]
@blakeembrey, sure, why not! :)

**Pull request merged**
