### PR TITLE
Fixes for IE

### PR DESCRIPTION
**Pull request by blink1073**
All tests now pass on IE11.

### CODE REVIEW

**Comment by blink1073** [comment]
This also exposed the fact that the other `init` methods need default values, or need to be removed.

**Comment by blakeembrey** [comment]
@blink1073 What does that mean (the default values or removed)? 

The change looks reasonable to me - is `event.bubbles` not overridable on IE?

**Comment by blink1073** [comment]
I mean I had to remove the test for `compositionend` because we were not passing sensible defaults to `initCompositionEvent`.  

As for why `event.bubbles` was not being set in `createEvent()`, I am not sure.

**Comment by blink1073** [comment]
Released as v1.3.0

**Pull request merged**
